#!/bin/bash

version=24.01

# Get dependencies
install_packages git xterm python3-pil python3-pil.imagetk python3-pip python3-psutil python3-distro python3-bs4 python3-dev python3-requests mpg123 lolcat wmctrl gdebi mousepad || exit 1

rm -rf ~/PiGro-Aid- || error "Failed to first remove ~/PiGro-Aid- folder!"
#Main Branch
#git_clone https://github.com/actionschnitzel/PiGro-Aid- -b $version --depth=1 || error "Failed to clone repository!"

#DEV Branch
git clone -b dev https://github.com/actionschnitzel/PiGro-Aid-.git

cd PiGro-Aid- || error "Failed to enter directory!"
chmod +x start.sh

cp -f $HOME/PiGro-Aid-/images/icons/logo.png $HOME/.local/share/icons/pigro-logo.png

mkdir -p $HOME/Desktop $HOME/.local/share/applications
echo "[Desktop Entry]
Name=PiGro
Comment=Raspberry Pi System Tool
Exec=$HOME/PiGro-Aid-/start.sh
Icon=$HOME/.local/share/pigro-logo.png
Terminal=false
StartupWMClass=PiGro
Type=Application
Categories=Utility;System;PackageManager;
StartupNotify=true" > ~/Desktop/pigro.desktop

chmod +x ~/Desktop/pigro.desktop

chmod 755 ~/Desktop/pigro.desktop
gio set ~/Desktop/pigro.desktop "metadata::trusted" yes

cp ~/Desktop/pigro.desktop ~/.local/share/applications/pigro.desktop
