keys_to_remove = [
    ".NET",
    "aarch64",
    "Adapta Gtk+ theme",
    "Adapta-Brila Gtk+ theme",
    "Adapta-Brila-Eta Gtk+ theme",
    "Adapta-Eta Gtk+ theme",
    "Adapta-Nokto Gtk+ theme",
    "Adapta-Nokto-Eta Gtk+ theme",
    "Adementary GTK+ theme",
    "ADLplug OPL/OPN",
    "adw-gtk3 Gtk Theme",
    "adw-gtk3 Gtk Theme",
    "adw-gtk3-dark Gtk Theme",
    "adw-gtk3-dark Gtk Theme",
    "Adwaita dark GTK theme",
    "Adwaita theme",
    "Adwaita theme",
    "Airwindows",
    "Akwa",
    "Akwa-dark",
    "Ambiance Gtk theme",
    "Apache JMeter help files",
    "Arc Gtk theme",
    "Arc-",
    "ArtyFX",
    "AVL Drumkits",
    "AVLDrums.lv2",
    "Base",
    "BaseExtension",
    "BasePlatform",
    "BaseSdk",
    "Bazel",
    "Bluray Java menus (BDJ) plugin for VLC",
    "Breeze GTK theme",
    "BYOD",
    "Calf",
    "CAPS",
    "Cardinal",
    "Catppuccin",
    "Chewing for Fcitx 5",
    "Chinese Addons",
    "ChowDSP-Plugins",
    "ChowTapeModel",
    "ChromiumAnwendungsbasis",
    "CMT",
    "Codecs",
    "Communitheme Gtk Theme",
    "Core",
    "CoreAction",
    "CoreArchiver",
    "CoreFM",
    "CoreHunt",
    "CoreImage",
    "CoreInfo",
    "CoreKeyboard",
    "CorePad",
    "CorePaint",
    "CorePDF",
    "CoreRenamer",
    "CoreShot",
    "CoreStats",
    "CoreTime",
    "CrosAdapta",
    "De Telegraaf-puzzelsets",
    "Deepin Gtk+ theme (dark)",
    "Deepin Gtk+ theme (dark)",
    "Deepin Gtk+ theme",
    "Deepin Gtk+ theme",
    "default",
    "Dexed",
    "DISTRHO-Ports",
    "DPF-Plugins",
    "DragonflyReverb",
    "DrumGizmo",
    "Dynamic Collections Plugin",
    "Electron2Anwendungsbasis",
    "electronAnwendungsbasis",
    "elementary stylesheet ",
    "elementary stylesheet",
    "elementaryAnwendungsbasis",
    "Fabla",
    "FDK-AAC Encoding Plugin for VLC",
    "ffmpeg-full",
    "FFMS2 Plugin",
    "Finnish Spellchecker",
    "Fire Distortion",
    "Flat-Remix",
    "Flat-Remix",
    "Free Pascal Compiler and Lazarus",
    "freedesktop Entwicklungsplattform Dokumentation",
    "Freedesktop Platform",
    "Freedesktop SDK",
    "gamescope",
    "Geonkick",
    "GimpLensfun",
    "GM Synth",
    "GNOME Application Platform version 3.38",
    "GNOME Application Platform version 44",
    "GNOME Application Platform version 45",
    "GNOME Application Platform",
    "GNOME Boxes Osinfo DB",
    "GNOME Crosswords Extra Puzzles",
    "gnome Entwicklungsplattform Dokumentation",
    "GNOME Software Development Kit version 3.38",
    "GNOME Software Development Kit version 3.38",
    "GNOME Software Development Kit version 44",
    "GNOME Software Development Kit version 44",
    "GNOME Software Development Kit version 45",
    "GNOME Software Development Kit version 45",
    "Go programming language Sdk extension",
    "Godot (C#/.NET)",
    "Godot 3",
    "Godot",
    "godotAnwendungsbasis",
    "Greybird GTK+ Theme",
    "Greybird-dark GTK+ Theme",
    "Greybird-Geeko GTK+ Theme",
    "gstreamer-vaapi",
    "Guitarix LV2",
    "GuitarML",
    "GxPlugins",
    "Haskell platform Sdk extension",
    "HEIC",
    "Helium Gtk Theme",
    "Helium-dark Gtk Theme",
    "Helm Synthesizer",
    "Help",
    "High Sierra GTK Theme",
    "HighContrast Theme",
    "iaito-radare2-webui",
    "iaito-translations",
    "Jade-1",
    "jc303",
    "KapitonovPluginsPack",
    "KDE Application Platform",
    "KDE Application Platform",
    "kde Entwicklungsplattform Dokumentation",
    "KDE Software Development Kit",
    "KDE Software Development Kit",
    "KiCad 3D Model Libraries",
    "KiCad Footprint Libraries",
    "KiCad Schematic Symbol Libraries",
    "KiCad Templates",
    "Kvantum theme engine",
    "ldc2",
    "LiquidRescale",
    "liriAnwendungsbasis",
    "LLVM",
    "Lounge gtk theme",
    "Lounge-compact gtk theme",
    "Lounge-night gtk theme",
    "Lounge-night-compact gtk theme",
    "LSP",
    "M17N for Fcitx 5",
    "MakeMKV plugin for VLC",
    "Maliit plugin for SailfishOS",
    "Maliit plugin for SailfishOS",
    "mariadb-connector-odbc",
    "master_me",
    "Matcha",
    "Materia",
    "McBopomofo for Fcitx 5",
    "MDA",
    "Mesa (Extra)",
    "Mesa",
    "MinGW-w64",
    "Mint-Y",
    "Mojave-GTK",
    "Mono",
    "Mozc for Fcitx 5",
    "Neural Amp Modeler",
    "Ninjas2",
    "Node.js",
    "Numix Frost Gtk Theme",
    "Numix Frost Light Gtk Theme",
    "Numix Gtk Theme",
    "nvidia",
    "Obsidian-2",
    "OCR",
    "Odin2",
    "Oedipus Crosswords",
    "openh264",
    "OpenJDK",
    "OpenJdk",
    "OpenMPT GStreamer Plugin",
    "OTR Plugin",
    "Pause Click plugin for VLC",
    "Perl Plugin",
    "PHP",
    "Plata theme",
    "Pop Gtk theme",
    "psqlodbc",
    "PyQt BaseApp",
    "QAdwaitaDecorations",
    "QGnomePlatform",
    "QGnomePlatform",
    "QGnomePlatform-decoration",
    "Qogir GTK theme",
    "Qogir-",
    "Qt Creator",
    "Qt Designer",
    "Qt Linguist",
    "Qt QDBusViewer",
    "Qt WebEngine BaseApp",
    "Qt WebEngine BaseApp",
    "Qt",
    "QtSNI",
    "QtSNI",
    "QtWebKit BaseApp",
    "qtwebkitAnwendungsbasis",
    "reMID",
    "Resynthesizer",
    "Rime for Fcitx 5",
    "Rust nightly Sdk extension",
    "Rust stable Sdk extension",
    "Rust stable",
    "rust-stable",
    "setBfree",
    "sfizz",
    "Sierra Negra GTK Theme",
    "So Synth LV2",
    "SolArc-Dark Gtk theme",
    "SonoBus VST3",
    "Sorcer",
    "sqliteodbc",
    "Stochas VST3",
    "sugarlabsAnwendungsbasis",
    "Surge Synthesizer",
    "Surge XT Synthesizer LV2/VST3/CLAP",
    "SWH",
    "TAP-plugins",
    "Telegram Desktop Webview Add-on",
    "theme",
    "Theme",
    "Tunefish4",
    "TypeScript",
    "Vala Sdk extension",
    "x42Plugins",
    "Yaru",
    "Yoshimi",
    "yt-dl totem-pl-parser plugin",
    "ZamPlugins",
    "Zhuyin For Fcitx 5",
    "Zig SDK Extension",
    "Zim Plugin",
    "Zukitre Gtk+ theme",
    "Zukitre Gtk+ theme",
    "Zukitwo Gtk+ theme",
    "ZynAddSubFx Synthesizer",
]
